# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 213f1950135459e2ad11f5d570d5975dac3a1ef2c976b31ba45f29a3277d4b976541828ac34111f1f964faa4a1e521bc377f22795ee6fe9c79341829c6dadbbc

test:
  secret_key_base: 04eb03a95961eb7b63b412ccde5daab350a45e98196ca1325eac88bb16bc9e51883a2dc748ac85d7248448df2d8dbcccd9e5924b4ada1034d1f6b674f97ded6c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
